[package]
name = "nomad-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.0"
ethers = { git = "https://github.com/gakonst/ethers-rs", branch = "master" }
ethers-signers = { git = "https://github.com/gakonst/ethers-rs", branch = "master", features = ["aws"] }
hex = "0.4.3"
once_cell = "1.8.0"
rusoto_core = "0.48.0"
rusoto_kms = "0.48.0"
tokio = "1.9.0"
serde_json = "1.0.66"
structopt = "0.3.23"

nomad-ethereum = { path = "../../chains/nomad-ethereum" }
nomad-core = { path = "../../nomad-core" }
nomad-base = { path = "../../nomad-base" }
